<?php
declare(strict_types=1);
require_once __DIR__.'/bootstrap.php';
function assert_public_http_url(string $url):string{$url=trim($url);if(!filter_var($url,FILTER_VALIDATE_URL))throw new RuntimeException('URLが不正です');$p=parse_url($url);if(!in_array(strtolower($p['scheme']??''),['http','https'],true))throw new RuntimeException('HTTP/HTTPSのみ利用できます');$ips=gethostbynamel((string)($p['host']??''))?:[];if(!$ips)throw new RuntimeException('ホストを解決できません');foreach($ips as $ip){if(!filter_var($ip,FILTER_VALIDATE_IP,FILTER_FLAG_NO_PRIV_RANGE|FILTER_FLAG_NO_RES_RANGE))throw new RuntimeException('内部ネットワーク宛URLは登録できません');}return $url;}
function http_get_feed(string $url):string{assert_public_http_url($url);$ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_TIMEOUT=>15,CURLOPT_CONNECTTIMEOUT=>8,CURLOPT_USERAGENT=>'Antennaize/1.0 RSS Fetcher',CURLOPT_HTTPHEADER=>['Accept: application/rss+xml, application/atom+xml, application/xml, text/xml;q=0.9'],CURLOPT_PROTOCOLS=>CURLPROTO_HTTP|CURLPROTO_HTTPS]);$body=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);$err=curl_error($ch);curl_close($ch);if($body===false||$status<200||$status>=300)throw new RuntimeException('RSS取得失敗 HTTP '.$status.' '.$err);if(strlen($body)>5*1024*1024)throw new RuntimeException('RSSサイズ上限超過');return $body;}
function parse_date(string $v):?string{if(trim($v)==='')return null;try{return(new DateTimeImmutable($v))->format('Y-m-d H:i:s');}catch(Throwable){return null;}}
function parse_feed(string $xml):array{libxml_use_internal_errors(true);$sx=simplexml_load_string($xml,SimpleXMLElement::class,LIBXML_NONET|LIBXML_NOCDATA);if(!$sx)throw new RuntimeException('XML解析失敗');$items=[];if(isset($sx->channel->item)){foreach($sx->channel->item as $i){$items[]=['title'=>trim((string)$i->title),'url'=>trim((string)$i->link),'published_at'=>parse_date((string)($i->pubDate??'')),'image_url'=>trim((string)($i->enclosure->attributes()->url??''))];}}else{foreach($sx->entry??[] as $e){$url='';foreach($e->link as $l){$a=$l->attributes();if((string)($a['rel']??'alternate')==='alternate'&&!empty($a['href'])){$url=(string)$a['href'];break;}}$items[]=['title'=>trim((string)$e->title),'url'=>trim($url),'published_at'=>parse_date((string)($e->published??$e->updated??'')),'image_url'=>''];}}return array_values(array_filter($items,fn($i)=>$i['title']!==''&&normalize_url($i['url'])!==''));}
function fetch_feed_row(array $f):int{$items=array_slice(parse_feed(http_get_feed((string)$f['feed_url'])),0,100);$stmt=db()->prepare('INSERT IGNORE INTO articles(antenna_id,feed_id,category_id,title,url,url_hash,image_url,published_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,NOW(),NOW())');$n=0;foreach($items as $i){$u=normalize_url($i['url']);if($u==='')continue;$stmt->execute([(int)$f['antenna_id'],(int)$f['id'],$f['category_id'],$i['title'],$u,url_hash($u),$i['image_url']?:null,$i['published_at']]);$n+=$stmt->rowCount();}db()->prepare('UPDATE feeds SET last_fetched_at=NOW(),last_error=NULL,updated_at=NOW() WHERE id=?')->execute([(int)$f['id']]);return $n;}
function fetch_due_feeds():array{$rows=db()->query("SELECT * FROM feeds WHERE is_active=1 AND(last_fetched_at IS NULL OR last_fetched_at<=DATE_SUB(NOW(),INTERVAL refresh_minutes MINUTE)) ORDER BY id")->fetchAll();$r=['feeds'=>0,'articles'=>0,'errors'=>[]];foreach($rows as $f){try{$r['articles']+=fetch_feed_row($f);$r['feeds']++;}catch(Throwable $e){db()->prepare('UPDATE feeds SET last_error=?,updated_at=NOW() WHERE id=?')->execute([$e->getMessage(),(int)$f['id']]);$r['errors'][]=['feed_id'=>(int)$f['id'],'error'=>$e->getMessage()];}}return $r;}
