<?php
declare(strict_types=1);
require_once __DIR__.'/bootstrap.php';
function migrate():void{
$sql=[
"CREATE TABLE IF NOT EXISTS admins(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,username VARCHAR(100) NOT NULL UNIQUE,password_hash VARCHAR(255) NOT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
"CREATE TABLE IF NOT EXISTS antennas(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(190) NOT NULL,type ENUM('livedoor','fc2','server') NOT NULL,host VARCHAR(255) NULL,subdomain VARCHAR(120) NULL,template_key VARCHAR(60) NOT NULL DEFAULT 'standard',description TEXT NULL,html_code MEDIUMTEXT NULL,css_code MEDIUMTEXT NULL,js_code MEDIUMTEXT NULL,platform_config JSON NULL,is_active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,UNIQUE KEY uq_host(host),KEY idx_type(type),KEY idx_active(is_active)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
"CREATE TABLE IF NOT EXISTS categories(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,antenna_id BIGINT UNSIGNED NOT NULL,name VARCHAR(120) NOT NULL,slug VARCHAR(120) NOT NULL,created_at DATETIME NOT NULL,UNIQUE KEY uq_category(antenna_id,slug),CONSTRAINT fk_category_antenna FOREIGN KEY(antenna_id) REFERENCES antennas(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
"CREATE TABLE IF NOT EXISTS feeds(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,antenna_id BIGINT UNSIGNED NOT NULL,category_id BIGINT UNSIGNED NULL,site_name VARCHAR(190) NOT NULL,site_url VARCHAR(2048) NULL,feed_url VARCHAR(2048) NOT NULL,refresh_minutes INT NOT NULL DEFAULT 60,is_active TINYINT(1) NOT NULL DEFAULT 1,last_fetched_at DATETIME NULL,last_error TEXT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,KEY idx_feed_antenna(antenna_id,is_active),CONSTRAINT fk_feed_antenna FOREIGN KEY(antenna_id) REFERENCES antennas(id) ON DELETE CASCADE,CONSTRAINT fk_feed_category FOREIGN KEY(category_id) REFERENCES categories(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
"CREATE TABLE IF NOT EXISTS articles(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,antenna_id BIGINT UNSIGNED NOT NULL,feed_id BIGINT UNSIGNED NOT NULL,category_id BIGINT UNSIGNED NULL,title TEXT NOT NULL,url VARCHAR(2048) NOT NULL,url_hash CHAR(64) NOT NULL,image_url VARCHAR(2048) NULL,published_at DATETIME NULL,is_adult TINYINT(1) NOT NULL DEFAULT 0,adult_mode TINYINT NOT NULL DEFAULT 0,is_deleted TINYINT(1) NOT NULL DEFAULT 0,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,UNIQUE KEY uq_article(antenna_id,url_hash),KEY idx_article_list(antenna_id,is_deleted,published_at),CONSTRAINT fk_article_antenna FOREIGN KEY(antenna_id) REFERENCES antennas(id) ON DELETE CASCADE,CONSTRAINT fk_article_feed FOREIGN KEY(feed_id) REFERENCES feeds(id) ON DELETE CASCADE,CONSTRAINT fk_article_category FOREIGN KEY(category_id) REFERENCES categories(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
"CREATE TABLE IF NOT EXISTS mutual_rss(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,antenna_id BIGINT UNSIGNED NOT NULL,name VARCHAR(190) NOT NULL,feed_url VARCHAR(2048) NOT NULL,display_limit INT NOT NULL DEFAULT 10,is_active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,KEY idx_mutual_antenna(antenna_id,is_active),CONSTRAINT fk_mutual_antenna FOREIGN KEY(antenna_id) REFERENCES antennas(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
"CREATE TABLE IF NOT EXISTS access_events(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,antenna_id BIGINT UNSIGNED NOT NULL,article_id BIGINT UNSIGNED NULL,event_type ENUM('in','out','pv','internal') NOT NULL,ref_host VARCHAR(255) NULL,ip_hash CHAR(64) NOT NULL,ua_hash CHAR(64) NOT NULL,is_fraud TINYINT(1) NOT NULL DEFAULT 0,created_at DATETIME NOT NULL,KEY idx_event_rank(antenna_id,event_type,created_at),KEY idx_event_article(article_id,event_type,created_at),CONSTRAINT fk_event_antenna FOREIGN KEY(antenna_id) REFERENCES antennas(id) ON DELETE CASCADE,CONSTRAINT fk_event_article FOREIGN KEY(article_id) REFERENCES articles(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
"CREATE TABLE IF NOT EXISTS rank_cache(antenna_id BIGINT UNSIGNED NOT NULL,cache_key VARCHAR(80) NOT NULL,payload MEDIUMTEXT NOT NULL,generated_at DATETIME NOT NULL,PRIMARY KEY(antenna_id,cache_key),CONSTRAINT fk_rank_antenna FOREIGN KEY(antenna_id) REFERENCES antennas(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"
];foreach($sql as $s)db()->exec($s);}
