<?php
declare(strict_types=1);
require_once __DIR__.'/../app/bootstrap.php';
require_once __DIR__.'/../app/rss.php';
admin_required();$message='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();try{$action=(string)($_POST['action']??'');
 if($action==='add_antenna'){$type=(string)$_POST['type'];if(!in_array($type,['livedoor','fc2','server'],true))throw new RuntimeException('種別が不正です');$s=db()->prepare('INSERT INTO antennas(name,type,host,subdomain,template_key,description,html_code,css_code,js_code,platform_config,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,NOW(),NOW())');$s->execute([trim($_POST['name']),$type,trim($_POST['host'])?:null,trim($_POST['subdomain'])?:null,trim($_POST['template_key'])?:'standard',trim($_POST['description'])?:null,'','','',json_encode([],JSON_UNESCAPED_UNICODE)]);$message='アンテナを作成しました';}
 elseif($action==='add_feed'){$url=assert_public_http_url((string)$_POST['feed_url']);$s=db()->prepare('INSERT INTO feeds(antenna_id,site_name,site_url,feed_url,refresh_minutes,created_at,updated_at) VALUES(?,?,?,?,?,NOW(),NOW())');$s->execute([(int)$_POST['antenna_id'],trim($_POST['site_name']),trim($_POST['site_url'])?:null,$url,max(10,(int)$_POST['refresh_minutes'])]);$message='RSSを登録しました';}
 elseif($action==='save_front'){$s=db()->prepare('UPDATE antennas SET html_code=?,css_code=?,js_code=?,updated_at=NOW() WHERE id=?');$s->execute([(string)$_POST['html_code'],(string)$_POST['css_code'],(string)$_POST['js_code'],(int)$_POST['antenna_id']]);$message='フロントコードを保存しました';}
 elseif($action==='add_mutual'){$url=assert_public_http_url((string)$_POST['feed_url']);$s=db()->prepare('INSERT INTO mutual_rss(antenna_id,name,feed_url,display_limit,created_at,updated_at) VALUES(?,?,?,?,NOW(),NOW())');$s->execute([(int)$_POST['antenna_id'],trim($_POST['name']),$url,max(1,min(100,(int)$_POST['display_limit']))]);$message='相互RSSを登録しました';}
 }catch(Throwable $e){$error=$e->getMessage();}}
$antennas=db()->query('SELECT * FROM antennas ORDER BY id DESC')->fetchAll();$selectedId=(int)($_GET['antenna']??($antennas[0]['id']??0));$selected=null;foreach($antennas as $a){if((int)$a['id']===$selectedId)$selected=$a;}$feeds=[];$mutual=[];if($selected){$s=db()->prepare('SELECT * FROM feeds WHERE antenna_id=? ORDER BY id DESC');$s->execute([$selectedId]);$feeds=$s->fetchAll();$s=db()->prepare('SELECT * FROM mutual_rss WHERE antenna_id=? ORDER BY id DESC');$s->execute([$selectedId]);$mutual=$s->fetchAll();}
?><!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Antennaize Admin</title><style>
body{margin:0;font-family:system-ui,sans-serif;background:#f4f6f8;color:#20242a}header{background:#16181d;color:#fff;padding:14px 22px;display:flex;justify-content:space-between}main{max-width:1320px;margin:auto;padding:22px}.grid{display:grid;grid-template-columns:300px 1fr;gap:20px}.card{background:#fff;border:1px solid #dfe3e8;border-radius:10px;padding:18px;margin-bottom:18px}input,select,textarea{width:100%;box-sizing:border-box;padding:9px;margin-top:5px}label{display:block;margin:10px 0}button{padding:9px 16px}.notice{padding:10px;border-radius:8px}.ok{background:#e8f7ee}.ng{background:#fdebec}.nav a{display:block;padding:9px;text-decoration:none;color:#222;border-bottom:1px solid #eee}.code{font-family:ui-monospace,monospace;min-height:220px}.two{display:grid;grid-template-columns:1fr 1fr;gap:12px}@media(max-width:800px){.grid,.two{grid-template-columns:1fr}}</style></head><body><header><strong>Antennaize Admin</strong><a href="logout.php" style="color:#fff">ログアウト</a></header><main>
<?php if($message):?><p class="notice ok"><?=e($message)?></p><?php endif;?><?php if($error):?><p class="notice ng"><?=e($error)?></p><?php endif;?><div class="grid"><aside><div class="card"><h2>アンテナ</h2><div class="nav"><?php foreach($antennas as $a):?><a href="?antenna=<?=(int)$a['id']?>"><?=e($a['name'])?> <small>(<?=e($a['type'])?>)</small></a><?php endforeach;?></div></div><div class="card"><h2>新規作成</h2><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="add_antenna"><label>名前<input name="name" required></label><label>種別<select name="type"><option value="server">server</option><option value="livedoor">livedoor</option><option value="fc2">fc2</option></select></label><label>Host<input name="host" placeholder="news.example.com"></label><label>サブドメイン<input name="subdomain" placeholder="news"></label><label>テンプレート<select name="template_key"><option>standard</option><option>compact</option><option>dark</option></select></label><label>説明<textarea name="description"></textarea></label><button>作成</button></form></div></aside><section>
<?php if($selected):?><div class="card"><h1><?=e($selected['name'])?></h1><p>種別: <?=e($selected['type'])?> / Host: <?=e($selected['host']?:'-')?> / Template: <?=e($selected['template_key'])?></p></div>
<div class="card"><h2>RSS登録</h2><form method="post" class="two"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="add_feed"><input type="hidden" name="antenna_id" value="<?=$selectedId?>"><label>サイト名<input name="site_name" required></label><label>サイトURL<input name="site_url" type="url"></label><label>RSS URL<input name="feed_url" type="url" required></label><label>更新間隔<select name="refresh_minutes"><?php foreach([10,30,60,120,180,360] as $m):?><option value="<?=$m?>" <?=$m===60?'selected':''?>><?=$m?>分</option><?php endforeach;?></select></label><button>登録</button></form><ul><?php foreach($feeds as $f):?><li><?=e($f['site_name'])?> — <?=e($f['feed_url'])?> <?php if($f['last_error']):?><strong><?=e($f['last_error'])?></strong><?php endif;?></li><?php endforeach;?></ul></div>
<div class="card"><h2>相互RSS</h2><form method="post" class="two"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="add_mutual"><input type="hidden" name="antenna_id" value="<?=$selectedId?>"><label>名称<input name="name" required></label><label>RSS URL<input type="url" name="feed_url" required></label><label>表示件数<input type="number" name="display_limit" value="10" min="1" max="100"></label><button>登録</button></form><ul><?php foreach($mutual as $m):?><li><?=e($m['name'])?> — <?=e($m['feed_url'])?></li><?php endforeach;?></ul></div>
<?php if(in_array($selected['type'],['livedoor','fc2'],true)):?><div class="card"><h2>ブログHTML / CSS</h2><p>Antennaize内の正本です。サービス側でテーマAPI更新ができない場合は、ここからコピーして反映します。</p><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="save_front"><input type="hidden" name="antenna_id" value="<?=$selectedId?>"><label>HTML<textarea class="code" name="html_code"><?=e($selected['html_code'])?></textarea></label><label>CSS<textarea class="code" name="css_code"><?=e($selected['css_code'])?></textarea></label><label>JavaScript<textarea class="code" name="js_code"><?=e($selected['js_code'])?></textarea></label><button>保存</button></form></div><?php endif;?>
<?php else:?><div class="card"><p>アンテナを作成してください。</p></div><?php endif;?></section></div></main></body></html>
